language: python
python:
    - "2.7"

install:
    - pip install --install-option="--no-cython-compile" Cython
    - "git clone https://github.com/ohinai/mimpy.git"
    - "cd mimpy; python setup.py install; cd .."
    - "pip install tox"
    - "pip install pytest"
    - "pip install matplotlib"

script:
    - tox
