language: python
python:
    - "2.7"

install:
    - "pip install tox"
    - "pip install pytest"
    - "pip install matplotlib"
    - "git clone https://github.com/ohinai/mimpy.git"
    - "python mimpy/setup.py install"

script:
    - tox
