language: python
python:
    - "2.7"
before_install:
    - 'pip install --install-option="--no-cython-compile" Cython'
    - "cd ~; git clone https://github.com/ohinai/mimpy.git"
    - "cd mimpy; python setup.py install; cd $TRAVIS_BUILD_DIR"
    
install:
    - "pip install tox"
    - "pip install pytest"
    - "pip install matplotlib"

script:
    - tox
